- docs/manual/runtime-container.md
> fix description of carina-node is incorrect

- README.md
- README_zh.md
> add roadmap link in readme

- Dockerfile
- Dockerfile.local
- Makefile
- README.md
- README_zh.md
- docs/manual/FAQ.md
- docs/manual/runtime-container.md
- go.mod
- go.sum
1. Supports multiple architecture image building
2. FAQ Adds bcache content
```release-note
Supports multiple architecture image building
```
> Supports multiple architecture image building

- docs/design/design-diskGroup.md
- docs/roadmap/roadmap.md
1.  Added node selection in disk group design
> Add a node for which the configuration takes effect

- .gitignore
- pkg/devicemanager/manager_test.go
>
> /kind bug
Fixes #32 
```release-note
none
```
> fix debug:make test

- examples/middleware/mysql.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
none
```
> make migrate pods test for mysql example

- README.md
- README_zh.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
none
```
> [docs] add blogs in readme

- docs/roadmap/roadmap.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
none
```
> [docs] mark RAID management as V1.0

- CONTRIBUTING.md
Signed-off-by: ZhenhuaZhang <zhangzhenhua@beyondcent.com>
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
none
```
> [docs] add CONTRIBUTING.md

- test/e2e/Makefile
- test/e2e/README.md
- test/e2e/framework/kubectl.go
- test/e2e/framework/pod.go
- test/e2e/framework/pvc.go
- test/e2e/framework/storageclass.go
- test/e2e/lvm/lvmpvc.go
add lvm pvc resizing,delete test
Fixes #
```release-note
none
```
> add lvm pvc resizing,delete test

- controllers/node_controller.go
> /kind bug
1、Delete used local variable **cacheNodeName** in node_controller.go.
2、Whether the PV is bound should be used to indirectly judge whether the PVC exists, then the global variable cacheNoDeleteLv has no great value and significance, and there is no logical mechanism for releasing its capacity. In theory, one day in the future, the application will be OOM.
3、When the PV recycling policy is retain, the pv and logicvolume will be keeped, the newly created PVC will be deleted by mistake.
Fixes #81 
```release-note
none
```
> refactor rebuild pvc

- CONTRIBUTING.md
Improve the contributing guide
Fixes #
```release-note
none
```
> docs:modify Contributing.md

- docs/manual/install.md
- docs/manual_zh/install.md
>
Fixes #
```release-note
none
```
> doc: correct the chart repo url

- test/e2e/framework/deployment.go
- test/e2e/framework/pvc.go
- test/e2e/lvm/block_lvm_pvc.go
- test/e2e/lvm/filesystem_lvm_pvc .go
add block mode pvc test case
Fixes #
```release-note
none
```
> add block mode pvc test case

- utils/iolimit/iolimit_test.go
> /kind bug
```release-note
none
```
> fix iolimit test

- controllers/logicvolume_controller.go
- debug/lvm-http-server/main.go
- debug/lvm-http-server/server/node.go
- docs/design/design-disk-manager.md
- pkg/devicemanager/lvmd/interface.go
- pkg/devicemanager/lvmd/lvm.go
- pkg/devicemanager/lvmd/parse.go
- pkg/devicemanager/troubleshoot/trouble.go
- pkg/devicemanager/volume/interface.go
- pkg/devicemanager/volume/volume.go
- utils/constants.go
> /kind bug
Fixes #96
```release-note
won't create thinpool
```
> remove thin pool

- cmd/carina-controller/run/node_metrics.go
- cmd/carina-controller/run/run.go
- cmd/carina-node/run/run.go
- pkg/csidriver/runners/metrics_exporter.go
> /kind bug
1. remove unused code
2. modify carina run context
3. resolve context deadline exceeded
Fixes #91
```release-note
none
```
> Fix stop carina

- charts/README.md
- charts/templates/csi-controller.yaml
- charts/templates/csi-driver.yaml
- charts/values.yaml
- controllers/node_controller.go
- deploy/kubernetes/csi-carina-controller.yaml
- deploy/kubernetes/csi-node-rbac.yaml
- test/e2e/deploycarina/csi-carina-controller.yaml
- test/e2e/deploycarina/csi-node-rbac.yaml
1、Carina don't need csi attacher.
2、If removing csi attach, can speed up container creation
```release-note
none
```
> remove csi attachment

- MAINTAINERS.md
- OWNERS
> Add Owner and Maintainers

- README.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
none
```
> [doc] change snapshot support to disabled

- deploy/kubernetes/csi-config-map.yaml
- test/e2e/Makefile
- test/e2e/deploycarina/crd-logicvolume.yaml
- test/e2e/deploycarina/crd-nodestoreresource.yaml
- test/e2e/deploycarina/csi-carina-node.yaml
- test/e2e/deploycarina/csi-config-map.yaml
- test/e2e/e2e.sh
update e2e deploy yaml,modify Makefile and e2e.sh
Fixes #
```release-note
none
```
> update e2e deploy yaml,modify Makefile and e2e.sh

- deploy/kubernetes/csi-carina-controller.yaml
> Modifying a Mirror Vault

- charts/values.yaml
>
> /kind bug
Fixes #
```release-note
fix chart deploy  with livessProbe 
```
> fix chart debug with livenessProbe

- charts/Chart.lock
- charts/Chart.yaml
- charts/templates/csi-node.yaml
- charts/values.yaml
>
> /kind bug
Fixes #129
```release-note
再初始化安装判断内核版本，大于3.10版本加载内核模块
```
> fix chart bug with modprobe

- charts/templates/csi-driver.yaml
- charts/values.yaml
>
> /kind bug
Fixes #
```release-note
multi livenessProbe image in value.yaml ,only keep one 
```
> fix chart debug with multi image error

- .github/workflows/ci.yaml
- test/e2e/deploycarina/csi-carina-controller.yaml
- test/e2e/deploycarina/csi-carina-node.yaml
add ci.yaml for github workflow
Fixes #
```release-note
none
```
> add ci.yaml

- .github/workflows/ci.yaml
modify ci security and build job
Fixes #
```release-note
none
```
> modify ci security and build job

- .github/workflows/ci.yaml
- test/e2e/deploycarina/csi-carina-controller.yaml
- test/e2e/deploycarina/csi-carina-node.yaml
modify ci job kubernetes
Fixes #
```release-note
none
```
> modify ci job kubernetes

- .github/workflows/ci.yaml
- test/e2e/deploycarina/csi-carina-controller.yaml
- test/e2e/deploycarina/csi-carina-node.yaml
- test/e2e/raw/block_raw_pvc.go
modify image pull policy
Fixes #
```release-note
none
```
> modify image pull policy

- README.md
- README_zh.md
> Add Kubernetes support range

- deploy/kubernetes/deploy.sh
> upgrade function

- pkg/devicemanager/partition/partition.go
- runners/devicecheck.go
- runners/nodestorageresource.go
- scheduler/schedulerplugin/localstorage/k8s.go
- scheduler/schedulerplugin/localstorage/storage-plugins.go
- scheduler/utils/utils.go
> /kind bug
1. refactor scheduler informer(first of all, get nsr/lv from cache, then from apiserver)
2. fix the bug 'can't use disk part to create pv'
```release-note
none
```
> refac: modify scheduler informer

- README.md
Signed-off-by: hwdef <hwdefcom@outlook.com>
/kind documentation
Ref https://github.com/cncf/toc/issues/974
> add code of conduct

- deploy/kubernetes/lvupgrade.sh
- pkg/devicemanager/partition/partition.go
Signed-off-by: antmoveh shen.ren.love@163.com
Modify a word
> Release 1.0

- docs/manual/capacity-scheduler.md
- docs/manual_zh/capacity-scheduler.md
>
Optimize capacity-scheduler.md document description.
Fixes #160
```release-note
none
```
> Optimize capacity-scheduler.md document description.

- README.md
- controllers/logicvolume_controller.go
- docs/manual/capacity-scheduler.md
- docs/manual_zh/capacity-scheduler.md
- pkg/devicemanager/volume/volume.go
- test/e2e/deploycarina/csi-carina-node.yaml
> Merge code

- docs/manual/metrics.md
- docs/manual_zh/metrics.md
- docs/user-guide.md
- examples/kubernetes/lvm-block-pvc.yaml
- examples/kubernetes/storageclass-raw.yaml
Signed-off-by: antmoveh <shen.ren.love@163.com>
>
> /kind bug
#159 
#162
Refine documentation, metrics, examples, etc
> update metrics docs

- deploy/kubernetes/deploy.sh
- deploy/kubernetes/lvupgrade.sh
Signed-off-by: antmoveh <shen.ren.love@163.com>
Fixes #
```release-note
optimize upgrade and deployment scripts
```
> optimize upgrade and deployment scripts

- cmd/carina-node/run/run.go
- deploy/kubernetes/lvupgrade.sh
- pkg/devicemanager/manager.go
- runners/troubleshoot.go
Signed-off-by: antmoveh <shen.ren.love@163.com>
>
> /kind bug
Fixes #
optimized and improved carina upgrade logic for major changes from low to high version
optimize disaster handing logic
> modifying carina v0.9.0-->0.11.x upgrade logic

- pkg/devicemanager/partition/partition.go
>
> /kind bug
Fixes #
```release-note
fix extend partition with raw  type,
```
> fix bug for raw exdedartition

- pkg/devicemanager/partition/partition.go
- pkg/devicemanager/partition/partition_test.go
>
> /kind bug
Fixes #
```release-note
fix debug with check mount point for targetpath 
```
> fix debug for exentend disk in checkout mount point for target path

- controllers/node_controller.go
>
> /kind bug
> /kind design
> /kind flake
/kind bug
optimization show log of skiplv in failover.
Fixes #177
```release-note
none
```
> fix: show log of skiplv in failover

- charts/templates/csi-node.yaml
Adding host /proc mount after error raised (testing on k8s 1.25).
Some whitespace autoremoval on edit.
> fix(node): missing proc mount

- charts/templates/rbac-cert.yaml
/kind bug
>
> /kind bug
> /kind design
> /kind flake
fix orphan cluster role
Fixes #210 
```release-note
none
```
> fix: orphan cluster role

- docs/knowledge_base/CSI/CSI应用参考.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
none
```
> docs: add 6.2 and 6.3 deployment methods
